export * from './form-task/form-task.component';
export * from './register/register.component';
export * from './footer/footer.component';
export * from './author/author.component';
export * from './login/login.component';
export * from './register/register.component';
export * from './list-tasks/list-tasks.component';
export * from './page-not-found/page-not-found.component';
export * from './header/header.component';
